//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapProxy.WebApiHost.TestWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://webservice.com")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoapProxy.WebApiHost.TestWebService.Contact[] ContactsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public SoapProxy.WebApiHost.TestWebService.Contact[] Contacts {
            get {
                return this.ContactsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactsField, value) != true)) {
                    this.ContactsField = value;
                    this.RaisePropertyChanged("Contacts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://webservice.com")]
    [System.SerializableAttribute()]
    public partial class Contact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfGuid", Namespace="http://webservice.com", ItemName="guid")]
    [System.SerializableAttribute()]
    public class ArrayOfGuid : System.Collections.Generic.List<System.Guid> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.com", ConfigurationName="TestWebService.AccountServiceSoap")]
    public interface AccountServiceSoap {
        
        // CODEGEN: 命名空间 http://webservice.com 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.com/HelloWorld", ReplyAction="*")]
        SoapProxy.WebApiHost.TestWebService.HelloWorldResponse HelloWorld(SoapProxy.WebApiHost.TestWebService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.com/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapProxy.WebApiHost.TestWebService.HelloWorldResponse> HelloWorldAsync(SoapProxy.WebApiHost.TestWebService.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://webservice.com 的元素名称 GetAccountResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.com/GetAccount", ReplyAction="*")]
        SoapProxy.WebApiHost.TestWebService.GetAccountResponse GetAccount(SoapProxy.WebApiHost.TestWebService.GetAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.com/GetAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapProxy.WebApiHost.TestWebService.GetAccountResponse> GetAccountAsync(SoapProxy.WebApiHost.TestWebService.GetAccountRequest request);
        
        // CODEGEN: 命名空间 http://webservice.com 的元素名称 ids 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.com/GetAccounts", ReplyAction="*")]
        SoapProxy.WebApiHost.TestWebService.GetAccountsResponse GetAccounts(SoapProxy.WebApiHost.TestWebService.GetAccountsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.com/GetAccounts", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapProxy.WebApiHost.TestWebService.GetAccountsResponse> GetAccountsAsync(SoapProxy.WebApiHost.TestWebService.GetAccountsRequest request);
        
        // CODEGEN: 命名空间 http://webservice.com 的元素名称 accounts 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.com/CreateAccounts", ReplyAction="*")]
        SoapProxy.WebApiHost.TestWebService.CreateAccountsResponse CreateAccounts(SoapProxy.WebApiHost.TestWebService.CreateAccountsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.com/CreateAccounts", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapProxy.WebApiHost.TestWebService.CreateAccountsResponse> CreateAccountsAsync(SoapProxy.WebApiHost.TestWebService.CreateAccountsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://webservice.com", Order=0)]
        public SoapProxy.WebApiHost.TestWebService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SoapProxy.WebApiHost.TestWebService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://webservice.com", Order=0)]
        public SoapProxy.WebApiHost.TestWebService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SoapProxy.WebApiHost.TestWebService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.com")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccount", Namespace="http://webservice.com", Order=0)]
        public SoapProxy.WebApiHost.TestWebService.GetAccountRequestBody Body;
        
        public GetAccountRequest() {
        }
        
        public GetAccountRequest(SoapProxy.WebApiHost.TestWebService.GetAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.com")]
    public partial class GetAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid id;
        
        public GetAccountRequestBody() {
        }
        
        public GetAccountRequestBody(System.Guid id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountResponse", Namespace="http://webservice.com", Order=0)]
        public SoapProxy.WebApiHost.TestWebService.GetAccountResponseBody Body;
        
        public GetAccountResponse() {
        }
        
        public GetAccountResponse(SoapProxy.WebApiHost.TestWebService.GetAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.com")]
    public partial class GetAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoapProxy.WebApiHost.TestWebService.Account GetAccountResult;
        
        public GetAccountResponseBody() {
        }
        
        public GetAccountResponseBody(SoapProxy.WebApiHost.TestWebService.Account GetAccountResult) {
            this.GetAccountResult = GetAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccounts", Namespace="http://webservice.com", Order=0)]
        public SoapProxy.WebApiHost.TestWebService.GetAccountsRequestBody Body;
        
        public GetAccountsRequest() {
        }
        
        public GetAccountsRequest(SoapProxy.WebApiHost.TestWebService.GetAccountsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.com")]
    public partial class GetAccountsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoapProxy.WebApiHost.TestWebService.ArrayOfGuid ids;
        
        public GetAccountsRequestBody() {
        }
        
        public GetAccountsRequestBody(SoapProxy.WebApiHost.TestWebService.ArrayOfGuid ids) {
            this.ids = ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountsResponse", Namespace="http://webservice.com", Order=0)]
        public SoapProxy.WebApiHost.TestWebService.GetAccountsResponseBody Body;
        
        public GetAccountsResponse() {
        }
        
        public GetAccountsResponse(SoapProxy.WebApiHost.TestWebService.GetAccountsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.com")]
    public partial class GetAccountsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoapProxy.WebApiHost.TestWebService.Account[] GetAccountsResult;
        
        public GetAccountsResponseBody() {
        }
        
        public GetAccountsResponseBody(SoapProxy.WebApiHost.TestWebService.Account[] GetAccountsResult) {
            this.GetAccountsResult = GetAccountsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAccountsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAccounts", Namespace="http://webservice.com", Order=0)]
        public SoapProxy.WebApiHost.TestWebService.CreateAccountsRequestBody Body;
        
        public CreateAccountsRequest() {
        }
        
        public CreateAccountsRequest(SoapProxy.WebApiHost.TestWebService.CreateAccountsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.com")]
    public partial class CreateAccountsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoapProxy.WebApiHost.TestWebService.Account[] accounts;
        
        public CreateAccountsRequestBody() {
        }
        
        public CreateAccountsRequestBody(SoapProxy.WebApiHost.TestWebService.Account[] accounts) {
            this.accounts = accounts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAccountsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAccountsResponse", Namespace="http://webservice.com", Order=0)]
        public SoapProxy.WebApiHost.TestWebService.CreateAccountsResponseBody Body;
        
        public CreateAccountsResponse() {
        }
        
        public CreateAccountsResponse(SoapProxy.WebApiHost.TestWebService.CreateAccountsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.com")]
    public partial class CreateAccountsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoapProxy.WebApiHost.TestWebService.Account[] CreateAccountsResult;
        
        public CreateAccountsResponseBody() {
        }
        
        public CreateAccountsResponseBody(SoapProxy.WebApiHost.TestWebService.Account[] CreateAccountsResult) {
            this.CreateAccountsResult = CreateAccountsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountServiceSoapChannel : SoapProxy.WebApiHost.TestWebService.AccountServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountServiceSoapClient : System.ServiceModel.ClientBase<SoapProxy.WebApiHost.TestWebService.AccountServiceSoap>, SoapProxy.WebApiHost.TestWebService.AccountServiceSoap {
        
        public AccountServiceSoapClient() {
        }
        
        public AccountServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapProxy.WebApiHost.TestWebService.HelloWorldResponse SoapProxy.WebApiHost.TestWebService.AccountServiceSoap.HelloWorld(SoapProxy.WebApiHost.TestWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SoapProxy.WebApiHost.TestWebService.HelloWorldRequest inValue = new SoapProxy.WebApiHost.TestWebService.HelloWorldRequest();
            inValue.Body = new SoapProxy.WebApiHost.TestWebService.HelloWorldRequestBody();
            SoapProxy.WebApiHost.TestWebService.HelloWorldResponse retVal = ((SoapProxy.WebApiHost.TestWebService.AccountServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapProxy.WebApiHost.TestWebService.HelloWorldResponse> SoapProxy.WebApiHost.TestWebService.AccountServiceSoap.HelloWorldAsync(SoapProxy.WebApiHost.TestWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapProxy.WebApiHost.TestWebService.HelloWorldResponse> HelloWorldAsync() {
            SoapProxy.WebApiHost.TestWebService.HelloWorldRequest inValue = new SoapProxy.WebApiHost.TestWebService.HelloWorldRequest();
            inValue.Body = new SoapProxy.WebApiHost.TestWebService.HelloWorldRequestBody();
            return ((SoapProxy.WebApiHost.TestWebService.AccountServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapProxy.WebApiHost.TestWebService.GetAccountResponse SoapProxy.WebApiHost.TestWebService.AccountServiceSoap.GetAccount(SoapProxy.WebApiHost.TestWebService.GetAccountRequest request) {
            return base.Channel.GetAccount(request);
        }
        
        public SoapProxy.WebApiHost.TestWebService.Account GetAccount(System.Guid id) {
            SoapProxy.WebApiHost.TestWebService.GetAccountRequest inValue = new SoapProxy.WebApiHost.TestWebService.GetAccountRequest();
            inValue.Body = new SoapProxy.WebApiHost.TestWebService.GetAccountRequestBody();
            inValue.Body.id = id;
            SoapProxy.WebApiHost.TestWebService.GetAccountResponse retVal = ((SoapProxy.WebApiHost.TestWebService.AccountServiceSoap)(this)).GetAccount(inValue);
            return retVal.Body.GetAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapProxy.WebApiHost.TestWebService.GetAccountResponse> SoapProxy.WebApiHost.TestWebService.AccountServiceSoap.GetAccountAsync(SoapProxy.WebApiHost.TestWebService.GetAccountRequest request) {
            return base.Channel.GetAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapProxy.WebApiHost.TestWebService.GetAccountResponse> GetAccountAsync(System.Guid id) {
            SoapProxy.WebApiHost.TestWebService.GetAccountRequest inValue = new SoapProxy.WebApiHost.TestWebService.GetAccountRequest();
            inValue.Body = new SoapProxy.WebApiHost.TestWebService.GetAccountRequestBody();
            inValue.Body.id = id;
            return ((SoapProxy.WebApiHost.TestWebService.AccountServiceSoap)(this)).GetAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapProxy.WebApiHost.TestWebService.GetAccountsResponse SoapProxy.WebApiHost.TestWebService.AccountServiceSoap.GetAccounts(SoapProxy.WebApiHost.TestWebService.GetAccountsRequest request) {
            return base.Channel.GetAccounts(request);
        }
        
        public SoapProxy.WebApiHost.TestWebService.Account[] GetAccounts(SoapProxy.WebApiHost.TestWebService.ArrayOfGuid ids) {
            SoapProxy.WebApiHost.TestWebService.GetAccountsRequest inValue = new SoapProxy.WebApiHost.TestWebService.GetAccountsRequest();
            inValue.Body = new SoapProxy.WebApiHost.TestWebService.GetAccountsRequestBody();
            inValue.Body.ids = ids;
            SoapProxy.WebApiHost.TestWebService.GetAccountsResponse retVal = ((SoapProxy.WebApiHost.TestWebService.AccountServiceSoap)(this)).GetAccounts(inValue);
            return retVal.Body.GetAccountsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapProxy.WebApiHost.TestWebService.GetAccountsResponse> SoapProxy.WebApiHost.TestWebService.AccountServiceSoap.GetAccountsAsync(SoapProxy.WebApiHost.TestWebService.GetAccountsRequest request) {
            return base.Channel.GetAccountsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapProxy.WebApiHost.TestWebService.GetAccountsResponse> GetAccountsAsync(SoapProxy.WebApiHost.TestWebService.ArrayOfGuid ids) {
            SoapProxy.WebApiHost.TestWebService.GetAccountsRequest inValue = new SoapProxy.WebApiHost.TestWebService.GetAccountsRequest();
            inValue.Body = new SoapProxy.WebApiHost.TestWebService.GetAccountsRequestBody();
            inValue.Body.ids = ids;
            return ((SoapProxy.WebApiHost.TestWebService.AccountServiceSoap)(this)).GetAccountsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapProxy.WebApiHost.TestWebService.CreateAccountsResponse SoapProxy.WebApiHost.TestWebService.AccountServiceSoap.CreateAccounts(SoapProxy.WebApiHost.TestWebService.CreateAccountsRequest request) {
            return base.Channel.CreateAccounts(request);
        }
        
        public SoapProxy.WebApiHost.TestWebService.Account[] CreateAccounts(SoapProxy.WebApiHost.TestWebService.Account[] accounts) {
            SoapProxy.WebApiHost.TestWebService.CreateAccountsRequest inValue = new SoapProxy.WebApiHost.TestWebService.CreateAccountsRequest();
            inValue.Body = new SoapProxy.WebApiHost.TestWebService.CreateAccountsRequestBody();
            inValue.Body.accounts = accounts;
            SoapProxy.WebApiHost.TestWebService.CreateAccountsResponse retVal = ((SoapProxy.WebApiHost.TestWebService.AccountServiceSoap)(this)).CreateAccounts(inValue);
            return retVal.Body.CreateAccountsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapProxy.WebApiHost.TestWebService.CreateAccountsResponse> SoapProxy.WebApiHost.TestWebService.AccountServiceSoap.CreateAccountsAsync(SoapProxy.WebApiHost.TestWebService.CreateAccountsRequest request) {
            return base.Channel.CreateAccountsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapProxy.WebApiHost.TestWebService.CreateAccountsResponse> CreateAccountsAsync(SoapProxy.WebApiHost.TestWebService.Account[] accounts) {
            SoapProxy.WebApiHost.TestWebService.CreateAccountsRequest inValue = new SoapProxy.WebApiHost.TestWebService.CreateAccountsRequest();
            inValue.Body = new SoapProxy.WebApiHost.TestWebService.CreateAccountsRequestBody();
            inValue.Body.accounts = accounts;
            return ((SoapProxy.WebApiHost.TestWebService.AccountServiceSoap)(this)).CreateAccountsAsync(inValue);
        }
    }
}
