//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="GoogleTranslateSoap", Namespace="http://tempuri.org/")]
public partial class GoogleTranslate : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback DetectOperationCompleted;
    
    private System.Threading.SendOrPostCallback TranslateOperationCompleted;
    
    /// <remarks/>
    public GoogleTranslate() {
        this.Url = "https://commservice_backend/translateservice/GoogleTranslate.asmx";
    }
    
    /// <remarks/>
    public event DetectCompletedEventHandler DetectCompleted;
    
    /// <remarks/>
    public event TranslateCompletedEventHandler TranslateCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Detect", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Detect(string auth, string text) {
        object[] results = this.Invoke("Detect", new object[] {
                    auth,
                    text});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDetect(string auth, string text, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Detect", new object[] {
                    auth,
                    text}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndDetect(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void DetectAsync(string auth, string text) {
        this.DetectAsync(auth, text, null);
    }
    
    /// <remarks/>
    public void DetectAsync(string auth, string text, object userState) {
        if ((this.DetectOperationCompleted == null)) {
            this.DetectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDetectOperationCompleted);
        }
        this.InvokeAsync("Detect", new object[] {
                    auth,
                    text}, this.DetectOperationCompleted, userState);
    }
    
    private void OnDetectOperationCompleted(object arg) {
        if ((this.DetectCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DetectCompleted(this, new DetectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Translate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string[] Translate(string auth, string[] texts, string sourceLanguage, string targetLanguage, bool isHtml) {
        object[] results = this.Invoke("Translate", new object[] {
                    auth,
                    texts,
                    sourceLanguage,
                    targetLanguage,
                    isHtml});
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginTranslate(string auth, string[] texts, string sourceLanguage, string targetLanguage, bool isHtml, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Translate", new object[] {
                    auth,
                    texts,
                    sourceLanguage,
                    targetLanguage,
                    isHtml}, callback, asyncState);
    }
    
    /// <remarks/>
    public string[] EndTranslate(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public void TranslateAsync(string auth, string[] texts, string sourceLanguage, string targetLanguage, bool isHtml) {
        this.TranslateAsync(auth, texts, sourceLanguage, targetLanguage, isHtml, null);
    }
    
    /// <remarks/>
    public void TranslateAsync(string auth, string[] texts, string sourceLanguage, string targetLanguage, bool isHtml, object userState) {
        if ((this.TranslateOperationCompleted == null)) {
            this.TranslateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTranslateOperationCompleted);
        }
        this.InvokeAsync("Translate", new object[] {
                    auth,
                    texts,
                    sourceLanguage,
                    targetLanguage,
                    isHtml}, this.TranslateOperationCompleted, userState);
    }
    
    private void OnTranslateOperationCompleted(object arg) {
        if ((this.TranslateCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.TranslateCompleted(this, new TranslateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void DetectCompletedEventHandler(object sender, DetectCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DetectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DetectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void TranslateCompletedEventHandler(object sender, TranslateCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class TranslateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal TranslateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string[])(this.results[0]));
        }
    }
}
