//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapClient.AccountService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://webservice.com")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoapClient.AccountService.Contact[] ContactsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public SoapClient.AccountService.Contact[] Contacts {
            get {
                return this.ContactsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactsField, value) != true)) {
                    this.ContactsField = value;
                    this.RaisePropertyChanged("Contacts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://webservice.com")]
    [System.SerializableAttribute()]
    public partial class Contact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfGuid", Namespace="http://webservice.com", ItemName="guid")]
    [System.SerializableAttribute()]
    public class ArrayOfGuid : System.Collections.Generic.List<System.Guid> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.com", ConfigurationName="AccountService.AccountServiceSoap")]
    public interface AccountServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://webservice.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.com/HelloWorld", ReplyAction="*")]
        SoapClient.AccountService.HelloWorldResponse HelloWorld(SoapClient.AccountService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.com/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapClient.AccountService.HelloWorldResponse> HelloWorldAsync(SoapClient.AccountService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetAccountResult from namespace http://webservice.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.com/GetAccount", ReplyAction="*")]
        SoapClient.AccountService.GetAccountResponse GetAccount(SoapClient.AccountService.GetAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.com/GetAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapClient.AccountService.GetAccountResponse> GetAccountAsync(SoapClient.AccountService.GetAccountRequest request);
        
        // CODEGEN: Generating message contract since element name ids from namespace http://webservice.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.com/GetAccounts", ReplyAction="*")]
        SoapClient.AccountService.GetAccountsResponse GetAccounts(SoapClient.AccountService.GetAccountsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.com/GetAccounts", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapClient.AccountService.GetAccountsResponse> GetAccountsAsync(SoapClient.AccountService.GetAccountsRequest request);
        
        // CODEGEN: Generating message contract since element name accounts from namespace http://webservice.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.com/CreateAccounts", ReplyAction="*")]
        SoapClient.AccountService.CreateAccountsResponse CreateAccounts(SoapClient.AccountService.CreateAccountsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.com/CreateAccounts", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapClient.AccountService.CreateAccountsResponse> CreateAccountsAsync(SoapClient.AccountService.CreateAccountsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://webservice.com", Order=0)]
        public SoapClient.AccountService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SoapClient.AccountService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://webservice.com", Order=0)]
        public SoapClient.AccountService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SoapClient.AccountService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.com")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccount", Namespace="http://webservice.com", Order=0)]
        public SoapClient.AccountService.GetAccountRequestBody Body;
        
        public GetAccountRequest() {
        }
        
        public GetAccountRequest(SoapClient.AccountService.GetAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.com")]
    public partial class GetAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid id;
        
        public GetAccountRequestBody() {
        }
        
        public GetAccountRequestBody(System.Guid id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountResponse", Namespace="http://webservice.com", Order=0)]
        public SoapClient.AccountService.GetAccountResponseBody Body;
        
        public GetAccountResponse() {
        }
        
        public GetAccountResponse(SoapClient.AccountService.GetAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.com")]
    public partial class GetAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoapClient.AccountService.Account GetAccountResult;
        
        public GetAccountResponseBody() {
        }
        
        public GetAccountResponseBody(SoapClient.AccountService.Account GetAccountResult) {
            this.GetAccountResult = GetAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccounts", Namespace="http://webservice.com", Order=0)]
        public SoapClient.AccountService.GetAccountsRequestBody Body;
        
        public GetAccountsRequest() {
        }
        
        public GetAccountsRequest(SoapClient.AccountService.GetAccountsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.com")]
    public partial class GetAccountsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoapClient.AccountService.ArrayOfGuid ids;
        
        public GetAccountsRequestBody() {
        }
        
        public GetAccountsRequestBody(SoapClient.AccountService.ArrayOfGuid ids) {
            this.ids = ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountsResponse", Namespace="http://webservice.com", Order=0)]
        public SoapClient.AccountService.GetAccountsResponseBody Body;
        
        public GetAccountsResponse() {
        }
        
        public GetAccountsResponse(SoapClient.AccountService.GetAccountsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.com")]
    public partial class GetAccountsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoapClient.AccountService.Account[] GetAccountsResult;
        
        public GetAccountsResponseBody() {
        }
        
        public GetAccountsResponseBody(SoapClient.AccountService.Account[] GetAccountsResult) {
            this.GetAccountsResult = GetAccountsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAccountsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAccounts", Namespace="http://webservice.com", Order=0)]
        public SoapClient.AccountService.CreateAccountsRequestBody Body;
        
        public CreateAccountsRequest() {
        }
        
        public CreateAccountsRequest(SoapClient.AccountService.CreateAccountsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.com")]
    public partial class CreateAccountsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoapClient.AccountService.Account[] accounts;
        
        public CreateAccountsRequestBody() {
        }
        
        public CreateAccountsRequestBody(SoapClient.AccountService.Account[] accounts) {
            this.accounts = accounts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAccountsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAccountsResponse", Namespace="http://webservice.com", Order=0)]
        public SoapClient.AccountService.CreateAccountsResponseBody Body;
        
        public CreateAccountsResponse() {
        }
        
        public CreateAccountsResponse(SoapClient.AccountService.CreateAccountsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.com")]
    public partial class CreateAccountsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoapClient.AccountService.Account[] CreateAccountsResult;
        
        public CreateAccountsResponseBody() {
        }
        
        public CreateAccountsResponseBody(SoapClient.AccountService.Account[] CreateAccountsResult) {
            this.CreateAccountsResult = CreateAccountsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountServiceSoapChannel : SoapClient.AccountService.AccountServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountServiceSoapClient : System.ServiceModel.ClientBase<SoapClient.AccountService.AccountServiceSoap>, SoapClient.AccountService.AccountServiceSoap {
        
        public AccountServiceSoapClient() {
        }
        
        public AccountServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapClient.AccountService.HelloWorldResponse SoapClient.AccountService.AccountServiceSoap.HelloWorld(SoapClient.AccountService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SoapClient.AccountService.HelloWorldRequest inValue = new SoapClient.AccountService.HelloWorldRequest();
            inValue.Body = new SoapClient.AccountService.HelloWorldRequestBody();
            SoapClient.AccountService.HelloWorldResponse retVal = ((SoapClient.AccountService.AccountServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapClient.AccountService.HelloWorldResponse> SoapClient.AccountService.AccountServiceSoap.HelloWorldAsync(SoapClient.AccountService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapClient.AccountService.HelloWorldResponse> HelloWorldAsync() {
            SoapClient.AccountService.HelloWorldRequest inValue = new SoapClient.AccountService.HelloWorldRequest();
            inValue.Body = new SoapClient.AccountService.HelloWorldRequestBody();
            return ((SoapClient.AccountService.AccountServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapClient.AccountService.GetAccountResponse SoapClient.AccountService.AccountServiceSoap.GetAccount(SoapClient.AccountService.GetAccountRequest request) {
            return base.Channel.GetAccount(request);
        }
        
        public SoapClient.AccountService.Account GetAccount(System.Guid id) {
            SoapClient.AccountService.GetAccountRequest inValue = new SoapClient.AccountService.GetAccountRequest();
            inValue.Body = new SoapClient.AccountService.GetAccountRequestBody();
            inValue.Body.id = id;
            SoapClient.AccountService.GetAccountResponse retVal = ((SoapClient.AccountService.AccountServiceSoap)(this)).GetAccount(inValue);
            return retVal.Body.GetAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapClient.AccountService.GetAccountResponse> SoapClient.AccountService.AccountServiceSoap.GetAccountAsync(SoapClient.AccountService.GetAccountRequest request) {
            return base.Channel.GetAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapClient.AccountService.GetAccountResponse> GetAccountAsync(System.Guid id) {
            SoapClient.AccountService.GetAccountRequest inValue = new SoapClient.AccountService.GetAccountRequest();
            inValue.Body = new SoapClient.AccountService.GetAccountRequestBody();
            inValue.Body.id = id;
            return ((SoapClient.AccountService.AccountServiceSoap)(this)).GetAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapClient.AccountService.GetAccountsResponse SoapClient.AccountService.AccountServiceSoap.GetAccounts(SoapClient.AccountService.GetAccountsRequest request) {
            return base.Channel.GetAccounts(request);
        }
        
        public SoapClient.AccountService.Account[] GetAccounts(SoapClient.AccountService.ArrayOfGuid ids) {
            SoapClient.AccountService.GetAccountsRequest inValue = new SoapClient.AccountService.GetAccountsRequest();
            inValue.Body = new SoapClient.AccountService.GetAccountsRequestBody();
            inValue.Body.ids = ids;
            SoapClient.AccountService.GetAccountsResponse retVal = ((SoapClient.AccountService.AccountServiceSoap)(this)).GetAccounts(inValue);
            return retVal.Body.GetAccountsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapClient.AccountService.GetAccountsResponse> SoapClient.AccountService.AccountServiceSoap.GetAccountsAsync(SoapClient.AccountService.GetAccountsRequest request) {
            return base.Channel.GetAccountsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapClient.AccountService.GetAccountsResponse> GetAccountsAsync(SoapClient.AccountService.ArrayOfGuid ids) {
            SoapClient.AccountService.GetAccountsRequest inValue = new SoapClient.AccountService.GetAccountsRequest();
            inValue.Body = new SoapClient.AccountService.GetAccountsRequestBody();
            inValue.Body.ids = ids;
            return ((SoapClient.AccountService.AccountServiceSoap)(this)).GetAccountsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapClient.AccountService.CreateAccountsResponse SoapClient.AccountService.AccountServiceSoap.CreateAccounts(SoapClient.AccountService.CreateAccountsRequest request) {
            return base.Channel.CreateAccounts(request);
        }
        
        public SoapClient.AccountService.Account[] CreateAccounts(SoapClient.AccountService.Account[] accounts) {
            SoapClient.AccountService.CreateAccountsRequest inValue = new SoapClient.AccountService.CreateAccountsRequest();
            inValue.Body = new SoapClient.AccountService.CreateAccountsRequestBody();
            inValue.Body.accounts = accounts;
            SoapClient.AccountService.CreateAccountsResponse retVal = ((SoapClient.AccountService.AccountServiceSoap)(this)).CreateAccounts(inValue);
            return retVal.Body.CreateAccountsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapClient.AccountService.CreateAccountsResponse> SoapClient.AccountService.AccountServiceSoap.CreateAccountsAsync(SoapClient.AccountService.CreateAccountsRequest request) {
            return base.Channel.CreateAccountsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapClient.AccountService.CreateAccountsResponse> CreateAccountsAsync(SoapClient.AccountService.Account[] accounts) {
            SoapClient.AccountService.CreateAccountsRequest inValue = new SoapClient.AccountService.CreateAccountsRequest();
            inValue.Body = new SoapClient.AccountService.CreateAccountsRequestBody();
            inValue.Body.accounts = accounts;
            return ((SoapClient.AccountService.AccountServiceSoap)(this)).CreateAccountsAsync(inValue);
        }
    }
}
