//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=4.8.3928.0。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="AndroidPushSoap", Namespace="http://hosted.comm100.com/AndroidPushNotification")]
public partial class AndroidPush : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback NewPushNotificationOperationCompleted;
    
    private System.Threading.SendOrPostCallback PushNotificationOperationCompleted;
    
    /// <remarks/>
    public AndroidPush() {
        this.Url = "https://commservice_backend/AndroidPushNotification/AndroidPush.asmx";
    }
    
    /// <remarks/>
    public event NewPushNotificationCompletedEventHandler NewPushNotificationCompleted;
    
    /// <remarks/>
    public event PushNotificationCompletedEventHandler PushNotificationCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hosted.comm100.com/AndroidPushNotification/NewPushNotification", RequestNamespace="http://hosted.comm100.com/AndroidPushNotification", ResponseNamespace="http://hosted.comm100.com/AndroidPushNotification", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void NewPushNotification([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] AndroidStructNotification[] notifications) {
        this.Invoke("NewPushNotification", new object[] {
                    notifications});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginNewPushNotification(AndroidStructNotification[] notifications, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("NewPushNotification", new object[] {
                    notifications}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndNewPushNotification(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void NewPushNotificationAsync(AndroidStructNotification[] notifications) {
        this.NewPushNotificationAsync(notifications, null);
    }
    
    /// <remarks/>
    public void NewPushNotificationAsync(AndroidStructNotification[] notifications, object userState) {
        if ((this.NewPushNotificationOperationCompleted == null)) {
            this.NewPushNotificationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNewPushNotificationOperationCompleted);
        }
        this.InvokeAsync("NewPushNotification", new object[] {
                    notifications}, this.NewPushNotificationOperationCompleted, userState);
    }
    
    private void OnNewPushNotificationOperationCompleted(object arg) {
        if ((this.NewPushNotificationCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.NewPushNotificationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hosted.comm100.com/AndroidPushNotification/PushNotification", RequestNamespace="http://hosted.comm100.com/AndroidPushNotification", ResponseNamespace="http://hosted.comm100.com/AndroidPushNotification", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void PushNotification([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] AndroidStructNotification[] notifications) {
        this.Invoke("PushNotification", new object[] {
                    notifications});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginPushNotification(AndroidStructNotification[] notifications, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("PushNotification", new object[] {
                    notifications}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndPushNotification(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void PushNotificationAsync(AndroidStructNotification[] notifications) {
        this.PushNotificationAsync(notifications, null);
    }
    
    /// <remarks/>
    public void PushNotificationAsync(AndroidStructNotification[] notifications, object userState) {
        if ((this.PushNotificationOperationCompleted == null)) {
            this.PushNotificationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPushNotificationOperationCompleted);
        }
        this.InvokeAsync("PushNotification", new object[] {
                    notifications}, this.PushNotificationOperationCompleted, userState);
    }
    
    private void OnPushNotificationOperationCompleted(object arg) {
        if ((this.PushNotificationCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.PushNotificationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hosted.comm100.com/AndroidPushNotification")]
public partial class AndroidStructNotification {
    
    private string _androidTokenField;
    
    private int _typeField;
    
    private string _alertMessageField;
    
    private long _visitorIdField;
    
    private string _visitorGuidField;
    
    private string _partnerIdField;
    
    /// <remarks/>
    public string _androidToken {
        get {
            return this._androidTokenField;
        }
        set {
            this._androidTokenField = value;
        }
    }
    
    /// <remarks/>
    public int _type {
        get {
            return this._typeField;
        }
        set {
            this._typeField = value;
        }
    }
    
    /// <remarks/>
    public string _alertMessage {
        get {
            return this._alertMessageField;
        }
        set {
            this._alertMessageField = value;
        }
    }
    
    /// <remarks/>
    public long _visitorId {
        get {
            return this._visitorIdField;
        }
        set {
            this._visitorIdField = value;
        }
    }
    
    /// <remarks/>
    public string _visitorGuid {
        get {
            return this._visitorGuidField;
        }
        set {
            this._visitorGuidField = value;
        }
    }
    
    /// <remarks/>
    public string _partnerId {
        get {
            return this._partnerIdField;
        }
        set {
            this._partnerIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void NewPushNotificationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void PushNotificationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
