//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ScreenSharingServiceSoap", Namespace="http://tempuri.org/")]
public partial class ScreenSharingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback CheckG2MLoginOperationCompleted;
    
    private System.Threading.SendOrPostCallback CreateG2MMeetingOperationCompleted;
    
    /// <remarks/>
    public ScreenSharingService() {
        this.Url = "https://commservice_backend/screensharingservice/ScreenSharingService.asmx";
    }
    
    /// <remarks/>
    public event CheckG2MLoginCompletedEventHandler CheckG2MLoginCompleted;
    
    /// <remarks/>
    public event CreateG2MMeetingCompletedEventHandler CreateG2MMeetingCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckG2MLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public StruResponse CheckG2MLogin(string email, string password) {
        object[] results = this.Invoke("CheckG2MLogin", new object[] {
                    email,
                    password});
        return ((StruResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCheckG2MLogin(string email, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CheckG2MLogin", new object[] {
                    email,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public StruResponse EndCheckG2MLogin(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((StruResponse)(results[0]));
    }
    
    /// <remarks/>
    public void CheckG2MLoginAsync(string email, string password) {
        this.CheckG2MLoginAsync(email, password, null);
    }
    
    /// <remarks/>
    public void CheckG2MLoginAsync(string email, string password, object userState) {
        if ((this.CheckG2MLoginOperationCompleted == null)) {
            this.CheckG2MLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckG2MLoginOperationCompleted);
        }
        this.InvokeAsync("CheckG2MLogin", new object[] {
                    email,
                    password}, this.CheckG2MLoginOperationCompleted, userState);
    }
    
    private void OnCheckG2MLoginOperationCompleted(object arg) {
        if ((this.CheckG2MLoginCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CheckG2MLoginCompleted(this, new CheckG2MLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateG2MMeeting", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public StruG2MResponse CreateG2MMeeting(string email, string password, string chatGuid) {
        object[] results = this.Invoke("CreateG2MMeeting", new object[] {
                    email,
                    password,
                    chatGuid});
        return ((StruG2MResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreateG2MMeeting(string email, string password, string chatGuid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreateG2MMeeting", new object[] {
                    email,
                    password,
                    chatGuid}, callback, asyncState);
    }
    
    /// <remarks/>
    public StruG2MResponse EndCreateG2MMeeting(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((StruG2MResponse)(results[0]));
    }
    
    /// <remarks/>
    public void CreateG2MMeetingAsync(string email, string password, string chatGuid) {
        this.CreateG2MMeetingAsync(email, password, chatGuid, null);
    }
    
    /// <remarks/>
    public void CreateG2MMeetingAsync(string email, string password, string chatGuid, object userState) {
        if ((this.CreateG2MMeetingOperationCompleted == null)) {
            this.CreateG2MMeetingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateG2MMeetingOperationCompleted);
        }
        this.InvokeAsync("CreateG2MMeeting", new object[] {
                    email,
                    password,
                    chatGuid}, this.CreateG2MMeetingOperationCompleted, userState);
    }
    
    private void OnCreateG2MMeetingOperationCompleted(object arg) {
        if ((this.CreateG2MMeetingCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateG2MMeetingCompleted(this, new CreateG2MMeetingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class StruResponse {
    
    private bool isSucceedField;
    
    private string responseField;
    
    /// <remarks/>
    public bool isSucceed {
        get {
            return this.isSucceedField;
        }
        set {
            this.isSucceedField = value;
        }
    }
    
    /// <remarks/>
    public string response {
        get {
            return this.responseField;
        }
        set {
            this.responseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class StruG2MResponse {
    
    private bool isSucceedField;
    
    private string errorMessageField;
    
    private string hostURLField;
    
    private string joinURLField;
    
    /// <remarks/>
    public bool isSucceed {
        get {
            return this.isSucceedField;
        }
        set {
            this.isSucceedField = value;
        }
    }
    
    /// <remarks/>
    public string errorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    public string hostURL {
        get {
            return this.hostURLField;
        }
        set {
            this.hostURLField = value;
        }
    }
    
    /// <remarks/>
    public string joinURL {
        get {
            return this.joinURLField;
        }
        set {
            this.joinURLField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void CheckG2MLoginCompletedEventHandler(object sender, CheckG2MLoginCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CheckG2MLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CheckG2MLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public StruResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((StruResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void CreateG2MMeetingCompletedEventHandler(object sender, CreateG2MMeetingCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreateG2MMeetingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreateG2MMeetingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public StruG2MResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((StruG2MResponse)(this.results[0]));
        }
    }
}
